
install! 'cocoapods'
use_frameworks!
platform :ios, '13.0'

target 'ChatSdk_Example' do
  pod 'ChatSdk', git: 'https://github.com/numanayhan/ChatSdk.git', branch: 'main'

  target 'ChatSdk_Tests' do
    inherit! :search_paths
    
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['SWIFT_VERSION'] = '5.5'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end
